from pathlib import Path
from itertools import product


# =====================================
# Workflow config items
configfile: "config/config.yaml"


WORKFLOW = Path("workflow").resolve()
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESULTS = Path("results").resolve()
RESOURCES = Path("resources").resolve()
LOGS = Path("logs/rules").resolve()
CONTAINERS = config["containers"]
GB = 1_024
PADDING: int = config["padding"]
KS: list[int] = config["pandora"]["ks"]
WS: list[int] = config["pandora"]["ws"]
WKS = [(w, k) for w, k in product(WS, KS) if w < k]
# =====================================

# =====================================
target_files = set()
for w, k in WKS:
    target_files.add(RESULTS / f"drprg/popn_prg/prgs/w{w}/k{k}/dr.prg.k{k}.w{w}.idx")


rule all:
    input:
        target_files,


# =====================================
rule index_reference:
    input:
        ref=RESOURCES / "NC_000962.3.fa",
    output:
        index=RESOURCES / "NC_000962.3.fa.fai",
    log:
        LOGS / "index_reference.log",
    container:
        CONTAINERS["samtools"]
    shell:
        "samtools faidx {input.ref} 2> {log}"


# =====================================
include: RULES / "panel.smk"
